service: hello-world

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20

package:
  artifact: /tmp/workspace/build/distributions/${self:service}.zip

functions:
  handler:
    handler: com.merricklabs.lambda.handlers.StreamLambdaHandler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true