import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * https://aws.amazon.com/lambda */
    const val aws_serverless_java_container_jersey: String =
            "com.amazonaws.serverless:aws-serverless-java-container-jersey:" +
            Versions.aws_serverless_java_container_jersey

    /**
     * https://aws.amazon.com/lambda/ */
    const val aws_lambda_java_core: String = "com.amazonaws:aws-lambda-java-core:" +
            Versions.aws_lambda_java_core

    /**
     * https://aws.amazon.com/lambda/ */
    const val aws_lambda_java_events: String = "com.amazonaws:aws-lambda-java-events:" +
            Versions.aws_lambda_java_events

    /**
     * https://aws.amazon.com/lambda/ */
    const val aws_lambda_java_log4j2: String = "com.amazonaws:aws-lambda-java-log4j2:" +
            Versions.aws_lambda_java_log4j2

    /**
     * http://github.com/FasterXML/jackson */
    const val jackson_annotations: String = "com.fasterxml.jackson.core:jackson-annotations:" +
            Versions.com_fasterxml_jackson_core

    /**
     * https://github.com/FasterXML/jackson-core */
    const val jackson_core: String = "com.fasterxml.jackson.core:jackson-core:" +
            Versions.com_fasterxml_jackson_core

    /**
     * http://github.com/FasterXML/jackson */
    const val jackson_databind: String = "com.fasterxml.jackson.core:jackson-databind:" +
            Versions.com_fasterxml_jackson_core

    /**
     * https://github.com/FasterXML/jackson-module-kotlin */
    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:" + Versions.jackson_module_kotlin

    /**
     * https://github.com/google/guava */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * https://github.com/nhaarman/mockito-kotlin */
    const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:" +
            Versions.mockito_kotlin

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

    /**
     * http://jaxb.java.net */
    const val jaxb_core: String = "com.sun.xml.bind:jaxb-core:" + Versions.com_sun_xml_bind

    /**
     * http://jaxb.java.net */
    const val jaxb_impl: String = "com.sun.xml.bind:jaxb-impl:" + Versions.com_sun_xml_bind

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/MicroUtils/kotlin-logging */
    const val kotlin_logging: String = "io.github.microutils:kotlin-logging:" +
            Versions.kotlin_logging

    /**
     * http://www.github.com/kotlintest/kotlintest */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    /**
     * http://java.sun.com/javase/technologies/desktop/javabeans/jaf/index.jsp */
    const val activation: String = "javax.activation:activation:" + Versions.activation

    /**
     * https://github.com/javaee/jaxb-spec */
    const val jaxb_api: String = "javax.xml.bind:jaxb-api:" + Versions.jaxb_api

    /**
     * http://hc.apache.org/httpcomponents-core-ga */
    const val httpcore: String = "org.apache.httpcomponents:httpcore:" + Versions.httpcore

    /**
     * https://projects.eclipse.org/projects/ee4j.jersey */
    const val jersey_container_grizzly2_http: String =
            "org.glassfish.jersey.containers:jersey-container-grizzly2-http:" +
            Versions.jersey_container_grizzly2_http

    /**
     * https://projects.eclipse.org/projects/ee4j.jersey */
    const val jersey_hk2: String = "org.glassfish.jersey.inject:jersey-hk2:" + Versions.jersey_hk2

    /**
     * https://projects.eclipse.org/projects/ee4j.jersey */
    const val jersey_media_json_jackson: String =
            "org.glassfish.jersey.media:jersey-media-json-jackson:" +
            Versions.jersey_media_json_jackson

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
            Versions.org_jetbrains_kotlin

    const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin

    /**
     * http://www.slf4j.org */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.org_slf4j

    /**
     * http://www.slf4j.org */
    const val slf4j_jdk14: String = "org.slf4j:slf4j-jdk14:" + Versions.org_slf4j

    /**
     * http://testng.org */
    const val testng: String = "org.testng:testng:" + Versions.testng
}
